<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.AspNet.SignalR.Client" Version="2.4.3" />
      <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
      <PackageReference Include="MongoDB.Driver" Version="3.4.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\DeviceEventHistory.Application\DeviceEventHistory.Application.csproj" />
      <ProjectReference Include="..\DeviceEventHistory.Domain\DeviceEventHistory.Domain.csproj" />
    </ItemGroup>

</Project>
