<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="MongoDB.Driver" Version="3.4.0" />
      <PackageReference Include="Microsoft.Data.SqlClient" Version="6.1.1" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\DeviceEventStatistics.Application\DeviceEventStatistics.Application.csproj" />
      <ProjectReference Include="..\DeviceEventStatistics.Domain\DeviceEventStatistics.Domain.csproj" />
    </ItemGroup>

</Project>
